#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

export PATH=$PATH:/usr/local/git/bin:/usr/local/bin
eval $(docker-machine env)

[[ -d ~/.rbenv  ]] && \
  export PATH=${HOME}/.rbenv/bin:${PATH} && \
  eval "$(rbenv init -)"

defaults write com.apple.dt.Xcode ShowBuildOperationDuration YES

[[ -d ~/.pyenv  ]] && \
  export PYENV_ROOT="$HOME/.pyenv" && \
  export PATH="$PYENV_ROOT/bin:$PATH" && \
  eval "$(pyenv init -)"

[[ -d ~/.nodebrew  ]] && \
  export PATH="$HOME/.nodebrew/current/bin:$PATH"

export PATH="/Applications/CMake.app/Contents/bin:$PATH"
